import 'swiper/scss/navigation'

import './globals.css'
import Footer from '@/components/Footer/Footer'
// import './home.css';
import Header from '@/components/Header/Header'

import 'swiper/scss'
import 'swiper/scss'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
