export { default as Home } from './Home/Home'
export { default as Delivery } from './Delivery/Delivery'
export { default as Company } from './Company/Company'
export { default as Warranty } from './Warranty/Warranty'
export { default as Product } from './Product/Product'
export { default as Service } from './Service/Service'
